### ISSUE TITLE
Add tests on Linux, macOS and Windows to CI/CD

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#873]
Running a CI job against multiple OS versions can be configured via a build matrix:

```yaml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
```

The above should be added to the `dotnet-core.yml` Action.
